Add mypy support and fixup project to give no errors
canopen-python/canopen pull request #512
Opened 2024-07-10 11:01 UTC by sveinse

With reference to #358 this PR is the starting point of adding typing with mypy support in canopen. It sets a recommended permissive starting point for mypy and it contains the absolute _minimal_ code change required to pass all mypy errors.

It does contain behavioral changes that were required to pass the tests. The majority of these fixes are more graceful handling of errors that would occur anyways, so the behavioral change is what error they produce.

* Add runtime test for `self.network` before using the network
* `PeriodicMessageTask.update()` don't stop the task unless it's running
* `Variable.desc` ensure that the object is int
* `Variable.read()` fail with ValueError unless a valid fmt is used
* `Variable.write()` ensure the description is a string
* `BaseNode.__init__()` fail if no node_id is provided
* `ObjectDictionary.__getitem__()` when splitting "." only return if the object is not an `ODVariable`
* `ODRecord.__eq__()`, `ODArray.__eq__()` and `ODVariable.__eq__()` test type of other before comparing
* `ODVariable.encode_raw()`, `.decode_phys()`, `.encode_phys()` add type tests of ensure the input is of correct type
* `PdoMap` various methods: ensure necessary attributes are not None

2024-07-10 11:04 UTC, erlend-aasland commented
This is great! Can you separate out all the behavioural changes in separate PRs accompanied with tests?

2024-07-10 11:07 UTC, erlend-aasland commented
Just to be explicit: in #358 there is an agreement on not mixing type annotations with other types of changes, including bug fixes and behavioural changes.

2024-07-10 11:30 UTC, sveinse commented
Yes, its possible to separate it out. While I see the intentions of separating out the type annotations from the behavioral changes, I'm not sure I like where this is going. Type annotating an existing project and behavioral changes goes iteratively hand in hand. Annotate something and an error pop up. Fix an error, and another annotation error appears. And so on. The sheer volume of PRs per behavioral change will be too great for me to handle. I won't be able to dedicate that much time to this. This PR is just a minor extract of what is to come ....at least if we're aiming for strict mypy. So perhaps we need to go back to #358 and really discuss what ambitions we have for type annotations to begin with.

2024-07-10 11:54 UTC, erlend-aasland commented
Yes, it is time-consuming, and it requires multiple PRs. IMO it is definitely worth it in the long run.

2024-07-10 11:56 UTC, acolomb commented
Yes, please let's first reach consensus on that discussion about the ambitions and the roadmap.  Will chime in there soon, but I can't afford looking at it every day right now.  Please have a little patience :-)

2024-07-10 12:07 UTC, sveinse commented
How many pieces must this PR be split into?

2024-07-10 12:26 UTC, erlend-aasland commented
> How many pieces must this PR be split into?

From a _quick_ glance at these changes, ISTM something like this is a sane approach[^1]:

- #511
- issue: discuss and agree on `add_node` / `create_node` changes
- issue (similar to gh-511): what to do in BaseNode when `node_id` is `None`
- issue (similar to the above): how to handle `cob_id` is `None` in PdoBase
- PR: add `WriteCallback` / `ReadCallback` protocols (I believe these should not be public APIs, no?)
- PR: harden OD encoding/decoding
- PR: harden OD equality operator

I might have missed some; there's _a lot_ of different types of changes here.

[^1]: For _each_ issue, time is best spent on reaching a consensus for a desired solution _before_ proposing a PR. Anything else is often a waste of reviewer time.

2024-07-10 12:29 UTC, erlend-aasland commented
When the above preparations have landed, it will be time to introduce annotations, which should then be a much easier PR to review, as it would do only one thing: introduce annotations.

2024-07-10 13:11 UTC, erlend-aasland commented
> The sheer volume of PRs per behavioral change will be too great for me to handle. I won't be able to dedicate that much time to this.

That's fine; this is open source. Let me know if you want me to help our with any of the preliminary tasks.

2024-07-10 14:59 UTC, sveinse commented
Please go ahead

2024-08-12 14:53 UTC, acolomb requested changes
Gradually working through this.  I had some of these fixes made locally as well, so trying to reconcile the bits and factor out into smaller PRs.  I haven't checked all touched files yet, will do so as time permits.

This should be merged with master, especially after #525 is sanctioned and merged.  It will reduce the diff a lot, making it easier to reason about.

2024-08-12 14:53 UTC, acolomb commented on canopen/emcy.py
> +    ) -> Optional[EmcyError]:
Cosmetics, let's keep these separate from the mypy error fixing.  There are lots of things like this to do, but better to keep a PR focused and revisit such cleanups later. IMHO.

2024-08-12 14:53 UTC, acolomb commented on canopen/emcy.py
> +            raise RuntimeError("A Network is required")
Superseded by #525?

2024-08-12 14:53 UTC, acolomb commented on canopen/network.py
> +            """ Dummy listener """
Fixed in master, I believe?

2024-08-12 14:53 UTC, acolomb commented on canopen/network.py
> +        self.notifier: Optional[can.Notifier] = None
Factored out to #534

2024-08-12 14:53 UTC, acolomb commented on canopen/network.py
> +            :class:`canopen.RemoteNode` object.
I think what is wrong here is the return type annotation.  It's perfectly alright to add an existing `LocalNode` to a network, isn't it?

2024-08-12 14:53 UTC, acolomb commented on canopen/network.py
> +            assert self._task is not None  # This will never be None, but mypy needs this
Superseded by #534

2024-08-12 14:53 UTC, acolomb commented on canopen/network.py
> +                self._task.stop()
Superseded by #534

2025-04-26 17:17 UTC, sveinse commented
I think we concluded on that this PR is not attractive, and that many of its sub-features are superseded by more specific PRs. I have no intentions on merging this PR, so I'm setting it to DRAFT. Yet, as a curious experiment, I updated the branch to reflect the current master to see how far the branch is from master. Perhaps we can get some inspirations for some new smaller PRs from it. Reminder of its goal: Get default mypy to pass without any error.

2025-06-14 12:39 UTC, closed without merging